# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20180123_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(default='Normal', max_length=10),
        ),
    ]
