# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20180123_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='user',
            new_name='to_user',
        ),
        migrations.AddField(
            model_name='msg',
            name='from_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
